version: 2.1
jobs:
  test:
    docker:
      - image: node:12
    steps:
      - checkout
      - run:
          command: yarn
          name: Install dependencies
      - run:
          command: yarn run test
          name: Run YARN tests
      - run:
          command: yarn run eslint ./src/*.ts ./src/*.tsx
          name: Check code style
workflows:
  test_app:
    jobs:
      - test
